name: xtremesports
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_sficon: ^1.1.2
  google_fonts: ^6.2.1
  sf_symbols: ^0.2.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/01-Yellow2.png
    - assets/02-Blue.png
    - assets/Splashscreengreen.png
    - assets/04-Orange.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Group 312.png"

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
  ios_content_mode: scaleAspectFill
